# Generated by Django 4.2.6 on 2023-11-03 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venta', '0004_carrito_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='username',
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.provincia'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.carrito'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.departamento'),
        ),
    ]
