# Generated by Django 4.2.6 on 2023-11-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_pedido_total_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('GUARDADO', 'Guardado'), ('PENDIENTE', 'Pendiente de compra')], default='GUARDADO', max_length=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
            ],
        ),
    ]
