# Generated by Django 4.2.6 on 2023-11-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_remove_carrito_cantidad_remove_carrito_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='estado',
        ),
    ]
