# Generated by Django 4.2.6 on 2023-11-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_remove_itemcarrito_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='estado',
            field=models.CharField(choices=[('GUARDADO', 'Guardado'), ('PENDIENTE', 'Pendiente de compra')], default='GUARDADO', max_length=10),
        ),
    ]
