# Generated by Django 4.2.6 on 2023-11-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_itemcarrito_cantidad_itemcarrito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
