# Generated by Django 4.2.6 on 2023-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_itemcarrito_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='pendiente_compra',
            field=models.BooleanField(default=True),
        ),
    ]
