# Generated by Django 4.2.6 on 2023-11-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_carrito_pendiente_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='pendiente_compra',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venta.producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
