# Generated by Django 4.2.6 on 2023-11-14 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_remove_carrito_pendiente_compra_carrito_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.producto'),
        ),
    ]
