# Generated by Django 4.2.6 on 2023-11-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_alter_carrito_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='username',
        ),
    ]
