# Generated by Django 4.2.6 on 2023-11-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_remove_pedidopersonalizado_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidopersonalizado',
            old_name='id_user',
            new_name='user',
        ),
    ]
