# Generated by Django 4.2.6 on 2023-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_rename_id_user_pedidopersonalizado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'estadoDeCarritos',
            },
        ),
    ]
