# Generated by Django 4.2.6 on 2023-11-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_paypalpago_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalpago',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='paypalpago',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paypalpago',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='paypalpago',
            name='total_carrito',
        ),
        migrations.AddField(
            model_name='paypalpago',
            name='billing_token',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='paypalpago',
            name='order_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='paypalpago',
            name='payer_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='paypalpago',
            name='payment_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
