# Generated by Django 4.2.6 on 2023-11-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0019_remove_paypalpago_contraseña_remove_paypalpago_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalpago',
            old_name='billing_token',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='paypalpago',
            old_name='order_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='paypalpago',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='paypalpago',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='paypalpago',
            name='id_carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.carrito'),
        ),
        migrations.AddField(
            model_name='paypalpago',
            name='total_carrito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
